name: 'Dependency Review'
on: [pull_request]
permissions:
  contents: read
  pull-requests: write
jobs:
  dependency-review:
    # Skip on fork since dependency graph may not be enabled
    if: github.repository == 'exa-labs/flyte'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
        continue-on-error: true
        with:
          comment-summary-in-pr: on-failure
          # Licenses need to come from https://spdx.org/licenses/
          deny-licenses: GPL-1.0-only, GPL-1.0-or-later, GPL-2.0-only, GPL-2.0-or-later, GPL-3.0-only, GPL-3.0-or-later

